FROM kmubigdata/ubuntu-cuda-cudnn
RUN apt-get update
RUN apt-get install -y python3-pip
RUN apt-get install -y python3-scipy
RUN apt-get install -y python3-tk
RUN pip3 install tensorflow-gpu scikit-learn pillow matplotlib keras
